name: workflow-run-metadata-action
description: Action to get a metadata on workflow_run event

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'
