name: workflow-run-summary-action
description: Get the summary of workflow run such as annotations, cancelled or skipped

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  annotation-messages:
    description: Annotation messages related to the workflow_run
  annotation-failure-messages:
    description: Annotation messages of failure only
  cancelled:
    description: true if any check run is cancelled
  skipped:
    description: true if all checks are skipped
  pull-request-number:
    description: Number of associated pull request, if exists
  pull-request-url:
    description: URL of associated pull request, if exists

runs:
  using: 'node20'
  main: 'dist/index.js'
