name: e2e

on:
  workflow_run:
    workflows:
      - e2e-fixture
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/workflow-run-summary-action@v1
        id: summary
      - run: echo "cancelled = ${{ steps.summary.outputs.cancelled }}"
      - run: echo "skipped = ${{ steps.summary.outputs.skipped }}"
      - run: echo "$SLACK_MESSAGE"
        env:
          SLACK_MESSAGE: ${{ steps.summary.outputs.annotation-messages }}
      - run: echo "$SLACK_MESSAGE"
        env:
          SLACK_MESSAGE: ${{ steps.summary.outputs.annotation-failure-messages }}
